### PR TITLE
Welcoming Artemis in hyperlap2d runtime

### PR DESCRIPTION
**Pull request by Minecraftian14**

### CODE REVIEW

**Comment by fgnm** [comment]
Hi Artemis and Goodby too :smile: 

Joking a part, bench on hyperlap runtime showed that Ashley is significantly faster compared to Artemis in `Engine` update but just little slower in world creation, we also have the problems that, in Artemis, `Systems` cannot be added or removed at runtime, which is not pratical... Artemis advantages at this point are quite useless for this runtime, so better to stay with Ashley

**Comment by Minecraftian14** [comment]
Painful to say, but well, after all the hard and messy work of converting the runtime from ashley to artemis, with the tests we took, it's best to not stay with Artemis... Ah, it's Artemis-odb, specifically 😅

Just posting what i believe can be useful if i ever refer to this issue again

Time for engine refers to the PooledSystem#update in Ashley and World#setDelta(Gdx.graphics.getDeltaTime()) and World#process.

Time for loadScene is SceneLoader#loadScene.

Test 1 - A very simple scene
image

Test 2 - A scene with a _lot_ of lights 😀
image

Test 3 - The space game in tutorials
image

No test were done for Artemis in Test 3 because no new systems can be added to a world instance while the game tries to. 
Reason? Well, systems are added using WorldConfigurationBuilder. And then the config is used to create a world. After that, the config is useless and the world is ineditable. 
A possible fix could be to not create the world right away, and add methods to add in new systems, finally creating the world with a separate method. But who cares now 🤣 Artemis is just not worth it.

**Comment by Minecraftian14** [comment]
Well.... somehow i felt that i should test things out on a game! So.. i did split the constructor in two

image

**Comment by Minecraftian14** [comment]
As of https://github.com/Minecraftian14/Hyperlap2D_TestingOutDifferentECS/tree/5a58f77f300c2b793e98d5bd429a24fd09ab82f8

image

image

image

Artemis has been winning by a small margin

**Pull request closed without merging**
